export { Login as LoginForm } from './login'
export { Register as RegisterForm, RegisterValuesProps } from './register'
export { ResetPass as ResetPassForm } from './reset-pass'
export { LostPass as LostPassForm } from './lost-pass'
export { CompanyForm, CompanyValuesProps } from './company-modal'
export { UserForm, UserValuesProps } from './personal-modal'
