version: '2'

services:
  bmp:
    build: .
    image: dev.ak5.cc:4567/kingqi/bmp
    container_name: bmp-app
    ports:
      - '3000:3000'
    env_file:
      - env/production.env
    volumes:
      - .:/opt/projects/bmp
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:alpine
    container_name: bmp-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    container_name: bmp-adminer
    restart: always
    ports:
      - 127.0.0.1:8011:8080
      
volumes: 
  pgdata:

