export const consts = {
    GET_UNCONFIRMED_COMPANIES_REQUSET: 'GET_UNCONFIRMED_COMPANIES_REQUSET',
    GET_UNCONFIRMED_COMPANIES_SUCCESS: 'GET_UNCONFIRMED_COMPANIES_SUCCESS',
    GET_UNCONFIRMED_COMPANIES_FAILURE: 'GET_UNCONFIRMED_COMPANIES_FAILURE',

    GET_CONFIRMING_COMPANY_REQUSET:'GET_CONFIRMING_COMPANY_REQUSET',
    GET_CONFIRMING_COMPANY_SUCCESS:'GET_CONFIRMING_COMPANY_SUCCESS',
    GET_CONFIRMING_COMPANY_FAILURE:'GET_CONFIRMING_COMPANY_FAILURE',

    CONFIRM_COMPANY_REQUSET: 'CONFIRM_COMPANY_REQUSET',
    CONFIRM_COMPANY_SUCCESS: 'CONFIRM_COMPANY_SUCCESS',
    CONFIRM_COMPANY_FAILURE: 'CONFIRM_COMPANY_FAILURE',

    DISCONFIRM_COMPANY_REQUSET: 'DISCONFIRM_COMPANY_REQUSET',
    DISCONFIRM_COMPANY_SUCCESS: 'DISCONFIRM_COMPANY_SUCCESS',
    DISCONFIRM_COMPANY_FAILURE: 'DISCONFIRM_COMPANY_FAILURE',
};
