export const consts = {
    UNCONFIRMED_COMPANIES_REQUSET: 'UNCONFIRMED_COMPANIES_REQUSET',
    UNCONFIRMED_COMPANIES_SUCCESS: 'UNCONFIRMED_COMPANIES_SUCCESS',
    UNCONFIRMED_COMPANIES_FAILURE: 'UNCONFIRMED_COMPANIES_FAILURE',

    CONFIRM_COMPANY_REQUSET: 'UNCONFIRMED_COMPANIES_REQUSET',
    CONFIRM_COMPANY_SUCCESS: 'UNCONFIRMED_COMPANIES_SUCCESS',
    CONFIRM_COMPANY_FAILURE: 'UNCONFIRMED_COMPANIES_FAILURE',
};
