export const consts = {
  GET_UNCONFIRMED_COMPANIES_REQUEST: 'GET_UNCONFIRMED_COMPANIES_REQUEST',
  GET_UNCONFIRMED_COMPANIES_SUCCESS: 'GET_UNCONFIRMED_COMPANIES_SUCCESS',
  GET_UNCONFIRMED_COMPANIES_FAILURE: 'GET_UNCONFIRMED_COMPANIES_FAILURE',

  GET_CONFIRMING_COMPANY_REQUEST: 'GET_CONFIRMING_COMPANY_REQUEST',
  GET_CONFIRMING_COMPANY_SUCCESS: 'GET_CONFIRMING_COMPANY_SUCCESS',
  GET_CONFIRMING_COMPANY_FAILURE: 'GET_CONFIRMING_COMPANY_FAILURE',

  CONFIRM_COMPANY_REQUEST: 'CONFIRM_COMPANY_REQUEST',
  CONFIRM_COMPANY_SUCCESS: 'CONFIRM_COMPANY_SUCCESS',
  CONFIRM_COMPANY_FAILURE: 'CONFIRM_COMPANY_FAILURE',

  DISCONFIRM_COMPANY_REQUEST: 'DISCONFIRM_COMPANY_REQUEST',
  DISCONFIRM_COMPANY_SUCCESS: 'DISCONFIRM_COMPANY_SUCCESS',
  DISCONFIRM_COMPANY_FAILURE: 'DISCONFIRM_COMPANY_FAILURE',

  GET_WAIT_FINISH_REQUEST: 'GET_WAIT_TRANSACTION_FINISH_REQUEST',
  GET_WAIT_FINISH_SUCCESS: 'GET_WAIT_TRANSACTION_FINISH_SUCCESS',
  GET_WAIT_FINISH_FAILURE: 'GET_WAIT_TRANSACTION_FINISH_FAILURE',

  GET_FINISHED_REQUEST: 'GET_TRANSACTION_FINISHED_REQUEST',
  GET_FINISHED_SUCCESS: 'GET_TRANSACTION_FINISHED_SUCCESS',
  GET_FINISHED_FAILURE: 'GET_TRANSACTION_FINISHED_FAILURE',

  FINISH_REQUEST: 'FINISH_TRANSACTION_REQUEST',
  FINISH_SUCCESS: 'FINISH_TRANSACTION_SUCCESS',
  FINISH_FAILURE: 'FINISH_TRANSACTION_FAILURE',

  IMAGE_TYPE_MEDIE: 1,
  IMAGE_TYPE_CERTIFICATE: 2,

  STATUS_CANCELLED: 0,
  STATUS_CREATED: 1,
  STATUS_FINISHED: 2,
  STATUS_TAKING: 3
}
