export const consts = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  LOGOUT: 'USER_LOGOUT',

  RESET_PASS_REQUEST: 'USER_RESET_PASS_REQUEST',
  RESET_PASS_SUCCESS: 'USER_RESET_PASS_SUCCESS',
  RESET_PASS_FAILURE: 'USER_RESET_PASS_FAILURE',

  REFRESH_AUTH_SUCCESS: 'REFRESH_AUTH_SUCCESS',
  REFRESH_AUTH_FAILURE: 'REFRESH_AUTH_FAILURE',

  LOST_PASS_REQUEST: 'USER_LOST_PASS_REQUEST',
  LOST_PASS_SUCCESS: 'USER_LOST_PASS_SUCCESS',
  LOST_PASS_FAILURE: 'USER_LOST_PASS_FAILURE',

  LICENSE_STATUS_UNCONFIRMED: 0,
  LICENSE_STATUS_CONFIRMED: 1,
  LICENSE_STATUS_DENIED: 2
}
