export const consts = {
  CREATE_REQUEST: 'GOODS_CREATE_REQUEST',
  CREATE_SUCCESS: 'GOODS_CREATE_SUCCESS',
  CREATE_FAILURE: 'GOODS_CREATE_FAILURE',

  EDIT_REQUEST: 'GOODS_EDIT_REQUEST',
  EDIT_SUCCESS: 'GOODS_EDIT_SUCCESS',
  EDIT_FAILURE: 'GOODS_EDIT_FAILURE',

  GET_REQUEST: 'GOODS_GET_REQUEST',
  GET_SUCCESS: 'GOODS_GET_SUCCESS',
  GET_FAILURE: 'GOODS_GET_FAILURE',

  GETALL_REQUEST: 'GOODS_GETALL_REQUEST',
  GETALL_SUCCESS: 'GOODS_GETALL_SUCCESS',
  GETALL_FAILURE: 'GOODS_GETALL_FAILURE',

  UPLOAD_REQUEST: 'GOODS_UPLOAD_REQUEST',
  UPLOAD_SUCCESS: 'GOODS_UPLOAD_SUCCESS',
  UPLOAD_FAILURE: 'GOODS_UPLOAD_FAILURE',

  CATEGORY: ['Beef', 'Veal', 'Sheep'],

  IMAGE_TYPE_MEDIE: 1,
  IMAGE_TYPE_CERTIFICATE: 2,

  LIST_PAGE_SIZE: 9
}
