export const consts = {
    CREATE_REQUEST : 'OFFER_CREATE_REQUEST',
    CREATE_SUCCESS : 'OFFER_CREATE_SUCCESS',
    CREATE_FAILURE : 'OFFER_CREATE_FAILURE',

    EDIT_REQUEST : 'OFFER_EDIT_REQUEST',
    EDIT_SUCCESS : 'OFFER_EDIT_SUCCESS',
    EDIT_FAILURE : 'OFFER_EDIT_FAILURE',

    GET_REQUEST : 'OFFER_GET_REQUEST',
    GET_SUCCESS : 'OFFER_GET_SUCCESS',
    GET_FAILURE : 'OFFER_GET_FAILURE',

    GETALL_REQUEST : 'OFFER_GETALL_REQUEST',
    GETALL_SUCCESS : 'OFFER_GETALL_SUCCESS',
    GETALL_FAILURE : 'OFFER_GETALL_FAILURE',

    CANCELL_REQUEST : 'OFFER_CANCELL_REQUEST',
    CANCELL_SUCCESS : 'OFFER_CANCELL_SUCCESS',
    CANCELL_FAILURE : 'OFFER_CANCELL_FAILURE',

    FINISH_REQUEST : 'OFFER_FINISH_REQUEST',
    FINISH_SUCCESS : 'OFFER_FINISH_SUCCESS',
    FINISH_FAILURE : 'OFFER_FINISH_FAILURE',

    UPLOAD_REQUEST : 'OFFER_UPLOAD_REQUEST',
    UPLOAD_SUCCESS : 'OFFER_UPLOAD_SUCCESS',
    UPLOAD_FAILURE : 'OFFER_UPLOAD_FAILURE',

    OFFER_TYPE: ["Beef","Veal","Sheep"],
    OFFER_STATUS_CANCELLED:0,
    OFFER_STATUS_CREATED:1,
    OFFER_STATUS_FINISHED:2,
};
