export const consts = {
    CREATE_REQUEST : 'ORDER_CREATE_REQUEST',
    CREATE_SUCCESS : 'ORDER_CREATE_SUCCESS',
    CREATE_FAILURE : 'ORDER_CREATE_FAILURE',

    EDIT_REQUEST : 'ORDER_EDIT_REQUEST',
    EDIT_SUCCESS : 'ORDER_EDIT_SUCCESS',
    EDIT_FAILURE : 'ORDER_EDIT_FAILURE',

    GET_REQUEST : 'ORDER_GET_REQUEST',
    GET_SUCCESS : 'ORDER_GET_SUCCESS',
    GET_FAILURE : 'ORDER_GET_FAILURE',

    GETALL_REQUEST : 'ORDER_GETALL_REQUEST',
    GETALL_SUCCESS : 'ORDER_GETALL_SUCCESS',
    GETALL_FAILURE : 'ORDER_GETALL_FAILURE',

    CANCELL_REQUEST : 'ORDER_CANCELL_REQUEST',
    CANCELL_SUCCESS : 'ORDER_CANCELL_SUCCESS',
    CANCELL_FAILURE : 'ORDER_CANCELL_FAILURE',

    COMMENT_REQUEST : 'ORDER_COMMENT_REQUEST',
    COMMENT_SUCCESS : 'ORDER_COMMENT_SUCCESS',
    COMMENT_FAILURE : 'ORDER_COMMENT_FAILURE',

    FINISH_REQUEST : 'ORDER_FINISH_REQUEST',
    FINISH_SUCCESS : 'ORDER_FINISH_SUCCESS',
    FINISH_FAILURE : 'ORDER_FINISH_FAILURE',

    ORDER_TYPE: ["Beef","Veal","Sheep"],
    ORDER_STATUS_CANCELLED:0,
    ORDER_STATUS_CREATED:1,
    ORDER_STATUS_FINISHED:2,
};
