export const consts = {
  CREATE_REQUEST: 'TRANSACTION_CREATE_REQUEST',
  CREATE_SUCCESS: 'TRANSACTION_CREATE_SUCCESS',
  CREATE_FAILURE: 'TRANSACTION_CREATE_FAILURE',

  CREATE_ORDER_REQUEST: 'ORDER_CREATE_REQUEST',
  CREATE_ORDER_SUCCESS: 'ORDER_CREATE_SUCCESS',
  CREATE_ORDER_FAILURE: 'ORDER_CREATE_FAILURE',

  EDIT_REQUEST: 'TRANSACTION_EDIT_REQUEST',
  EDIT_SUCCESS: 'TRANSACTION_EDIT_SUCCESS',
  EDIT_FAILURE: 'TRANSACTION_EDIT_FAILURE',

  GET_REQUEST: 'TRANSACTION_GET_REQUEST',
  GET_SUCCESS: 'TRANSACTION_GET_SUCCESS',
  GET_FAILURE: 'TRANSACTION_GET_FAILURE',

  GETALL_REQUEST: 'TRANSACTION_GETALL_REQUEST',
  GETALL_SUCCESS: 'TRANSACTION_GETALL_SUCCESS',
  GETALL_FAILURE: 'TRANSACTION_GETALL_FAILURE',

  CANCEL_REQUEST: 'TRANSACTION_CANCEL_REQUEST',
  CANCEL_SUCCESS: 'TRANSACTION_CANCEL_SUCCESS',
  CANCEL_FAILURE: 'TRANSACTION_CANCEL_FAILURE',

  REACTIVATE_REQUEST: 'TRANSACTION_REACTIVATE_REQUEST',
  REACTIVATE_SUCCESS: 'TRANSACTION_REACTIVATE_SUCCESS',
  REACTIVATE_FAILURE: 'TRANSACTION_REACTIVATE_FAILURE',

  FINISH_REQUEST: 'TRANSACTION_FINISH_REQUEST',
  FINISH_SUCCESS: 'TRANSACTION_FINISH_SUCCESS',
  FINISH_FAILURE: 'TRANSACTION_FINISH_FAILURE',

  UPLOAD_REQUEST: 'TRANSACTION_UPLOAD_REQUEST',
  UPLOAD_SUCCESS: 'TRANSACTION_UPLOAD_SUCCESS',
  UPLOAD_FAILURE: 'TRANSACTION_UPLOAD_FAILURE',

  COMMENT_REQUEST: 'TRANSACTION_COMMENT_REQUEST',
  COMMENT_SUCCESS: 'TRANSACTION_COMMENT_SUCCESS',
  COMMENT_FAILURE: 'TRANSACTION_COMMENT_FAILURE',

  CATEGORY: ['Beef', 'Veal', 'Sheep'],
  TYPE_BUY: 'Buy',
  TYPE_SELL: 'Sell',
  STATUS_CANCELLED: 0,
  STATUS_CREATED: 1,
  STATUS_FINISHED: 2,

  IMAGE_TYPE_MEDIE: 1,
  IMAGE_TYPE_CERTIFICATE: 2,

  LIST_PAGE_SIZE: 9
}
