export const consts = {
    UPLOAD_IMAGE_REQUEST : 'UPLOAD_IMAGE_REQUEST',
    UPLOAD_IMAGE_SUCCESS : 'UPLOAD_IMAGE_SUCCESS',
    UPLOAD_IMAGE_FAILURE : 'UPLOAD_IMAGE_FAILURE',
    UPLOAD_CLEAR_IMAGE : 'UPLOAD_CLEAR_IMAGE'
};
