export const consts = {
  UPLOAD_IMAGE_REQUEST: 'UPLOAD_IMAGE_REQUEST',
  UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
  UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',
<<<<<<< b3cf273bdbd82a1ddd0dffac4a9b73e955cb4bd5
  UPLOAD_CLEAR_IMAGE: 'UPLOAD_CLEAR_IMAGE'
=======
  UPLOAD_CLEAR_IMAGE: 'UPLOAD_CLEAR_IMAGE',
>>>>>>> format code
}
