export const consts = {
  UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

  GET_REQUEST: 'USER_GET_REQUEST',
  GET_SUCCESS: 'USER_GET_SUCCESS',
  GET_FAILURE: 'USER_GET_FAILURE',

  CREATE_CONSIGNEE_REQUEST: 'CONSIGNEE_CREATE_REQUEST',
  CREATE_CONSIGNEE_SUCCESS: 'CONSIGNEE_CREATE_SUCCESS',
  CREATE_CONSIGNEE_FAILURE: 'CONSIGNEE_CREATE_FAILURE',

  EDIT_CONSIGNEE_REQUEST: 'CONSIGNEE_EDIT_REQUEST',
  EDIT_CONSIGNEE_SUCCESS: 'CONSIGNEE_EDIT_SUCCESS',
  EDIT_CONSIGNEE_FAILURE: 'CONSIGNEE_EDIT_FAILURE',

  DELETE_CONSIGNEE_REQUEST: 'CONSIGNEE_DELETE_REQUEST',
  DELETE_CONSIGNEE_SUCCESS: 'CONSIGNEE_DELETE_SUCCESS',
  DELETE_CONSIGNEE_FAILURE: 'CONSIGNEE_DELETE_FAILURE',

  SET_DEFAULT_CONSIGNEE_REQUEST: 'USER_SET_DEFAULT_CONSIGNEE_REQUEST',
  SET_DEFAULT_CONSIGNEE_SUCCESS: 'USER_SET_DEFAULT_CONSIGNEE_SUCCESS',
  SET_DEFAULT_CONSIGNEE_FAILURE: 'USER_SET_DEFAULT_CONSIGNEE_FAILURE',

  USER_TYPE_NORMAL: 0,
  USER_TYPE_ADMIN: 1
}
