export const consts = {
    UPDATE_REQUEST : 'USER_UPDATE_REQUEST',
    UPDATE_SUCCESS : 'USER_UPDATE_SUCCESS',
    UPDATE_FAILURE : 'USER_UPDATE_FAILURE',

    LOGIN_REQUEST : 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE : 'USER_LOGIN_FAILURE',

    REGISTER_REQUEST : 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS : 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE : 'USER_REGISTER_FAILURE',

    LOGOUT : 'USER_LOGOUT',

    GETALL_REQUEST : 'USER_GETALL_REQUEST',
    GETALL_SUCCESS : 'USER_GETALL_SUCCESS',
    GETALL_FAILURE : 'USER_GETALL_FAILURE',

    GET_REQUEST : 'USER_GET_REQUEST',
    GET_SUCCESS : 'USER_GET_SUCCESS',
    GET_FAILURE : 'USER_GET_FAILURE',

    DELETE_REQUEST : 'USER_DELETE_REQUEST',
    DELETE_SUCCESS : 'USER_DELETE_SUCCESS',
    DELETE_FAILURE : 'USER_DELETE_FAILURE',

    LOST_PASS_REQUEST : 'USER_LOST_PASS_REQUEST',
    LOST_PASS_SUCCESS : 'USER_LOST_PASS_SUCCESS',
    LOST_PASS_FAILURE : 'USER_LOST_PASS_FAILURE',

    RESET_PASS_REQUEST : 'USER_RESET_PASS_REQUEST',
    RESET_PASS_SUCCESS : 'USER_RESET_PASS_SUCCESS',
    RESET_PASS_FAILURE : 'USER_RESET_PASS_FAILURE',

    USER_TYPE_NORMAL: 0,
    USER_TYPE_ADMIN: 1
};
