export const consts = {
  USER_TYPE_NORMAL: 0,
  USER_TYPE_ADMIN: 1,

  TRANSACTION_STATUS_CANCELLED: 0,
  TRANSACTION_STATUS_CREATED: 1,
  TRANSACTION_STATUS_FINISHED: 2,
  TRANSACTION_STATUS_TAKING: 3,

  LICENSE_STATUS_UNCONFIRMED: 0,
  LICENSE_STATUS_CONFIRMED: 1,
  LICENSE_STATUS_DENIED: 2,

  PROOFSTATUS_UNCONFIRMED: 0,
  PROOFSTATUS_CONFIRMED: 1,
  PROOFSTATUS_DENIED: 2,

  IMAGE_TYPE_MEDIA: 1,
  IMAGE_TYPE_CERTIFICATE: 2,

  TRANSACTION_TYPE_BUY: 'Buy',
  TRANSACTION_TYPE_SELL: 'Sell',

  EXPIRE_IN: 60 * 60 * 24 * 7 // 7 days
}
export const accessKey = 'db7b00b340d9275681a88e2398428a37'
export const currencySymbols = ['CNY', 'EUR', 'USD', 'GBP', 'JPY', 'KRW', 'FRF']
